### ISSUE TITLE
Possible link path Problem

### ISSUE THREAD

**Issue by IP-CAM** [rkostyuchenko/safes-oc-theme#1]
in your Code, the Link looks like this:
catalog/view/theme/THEME_SLUG/....
Should it not better look like this:
catalog/view/theme/theme_slug/....

**Comment by rkostyuchenko** [comment]
When building `THEME_SLUG` is [replaced](https://github.com/rkostyuchenko/safes-oc-theme/blob/58c6dce92f85433ed3f77556f1b7ff202b383d09/config/gulp/tasks/copy.js#L51) by the value from the [settings](https://github.com/rkostyuchenko/safes-oc-theme/blob/58c6dce92f85433ed3f77556f1b7ff202b383d09/config/settings.js#L3)

**Comment by IP-CAM** [comment]
ok, thanks for the info
